steps:
- name: 'hashicorp/terraform:1.0.0'
  id: 'tf plan'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "branch $BRANCH_NAME"
      if [ ! -z "BRANCH_NAME" -a -d "column-level-security/dev/my_dataset/mytable" ]; then
        cd column-level-security/dev/my_dataset/mytable/
        echo "run init"
        terraform init
        echo "validate"
        terraform validate
        echo "run plan"
        terraform plan -out terraform.plan
        terraform apply --auto-approve terraform.plan
      elif [! -z "BRANCH_NAME" -a -d "column-level-security/dev/my_dataset/mytable_copy" ]; then
        cd column-level-security/dev/my_dataset/mytable/mydataset_copy
        echo "run init"
        terraform init
        echo "validate"
        terraform validate
        echo "run plan"
        terraform plan -out terraform.plan
        terraform apply --auto-approve terraform.plan
      done
      fi
options:
  logging: CLOUD_LOGGING_ONLY
